# Generated by Django 6.0.4 on 2026-04-30 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('sales', '0001_initial'),
        ('shops', '0003_shop_domain_epoch_shop_invite_code_shop_migrated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepayment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_payments', to='shops.shop'),
        ),
        migrations.AddIndex(
            model_name='salepayment',
            index=models.Index(fields=['shop', 'occurred_at'], name='payments_sa_shop_id_cdb4e8_idx'),
        ),
        migrations.AddIndex(
            model_name='salepayment',
            index=models.Index(fields=['sale', 'occurred_at'], name='payments_sa_sale_id_c65e95_idx'),
        ),
        migrations.AddIndex(
            model_name='salepayment',
            index=models.Index(fields=['shop', 'payment_method'], name='payments_sa_shop_id_dd2e4a_idx'),
        ),
    ]
