# Generated by Django 6.0.4 on 2026-05-01 12:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('sales', '0001_initial'),
        ('shops', '0003_shop_domain_epoch_shop_invite_code_shop_migrated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePaymentCommandReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command_id', models.CharField(max_length=128)),
                ('source_surface', models.CharField(blank=True, max_length=64)),
                ('base_domain_epoch', models.PositiveIntegerField(default=1)),
                ('result_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=16)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_payment_command_receipts', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_receipt', to='payments.salepayment')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_command_receipts', to='sales.sale')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_payment_command_receipts', to='shops.shop')),
            ],
            options={
                'ordering': ['-applied_at', '-created_at'],
                'indexes': [models.Index(fields=['shop', 'applied_at'], name='payments_sa_shop_id_5c87f0_idx'), models.Index(fields=['shop', 'result_status'], name='payments_sa_shop_id_8bb92b_idx'), models.Index(fields=['sale', 'applied_at'], name='payments_sa_sale_id_bf735d_idx')],
                'constraints': [models.UniqueConstraint(fields=('shop', 'command_id'), name='uniq_sale_payment_command_receipt_per_shop')],
            },
        ),
    ]
