# Generated by Django 6.0.4 on 2026-04-30 12:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('shops', '0003_shop_domain_epoch_shop_invite_code_shop_migrated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDashboardSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_items_count', models.PositiveIntegerField(default=0)),
                ('active_inventory_items_count', models.PositiveIntegerField(default=0)),
                ('category_count', models.PositiveIntegerField(default=0)),
                ('low_stock_items_count', models.PositiveIntegerField(default=0)),
                ('out_of_stock_items_count', models.PositiveIntegerField(default=0)),
                ('projected_sell_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('customer_count', models.PositiveIntegerField(default=0)),
                ('active_credit_customers_count', models.PositiveIntegerField(default=0)),
                ('total_outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_lifetime_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('outstanding_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payment_count', models.PositiveIntegerField(default=0)),
                ('total_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit_payment_count', models.PositiveIntegerField(default=0)),
                ('digital_payment_count', models.PositiveIntegerField(default=0)),
                ('last_sale_at', models.DateTimeField(blank=True, null=True)),
                ('refreshed_at', models.DateTimeField()),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_snapshot', to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopLowStockSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=128)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('stock_on_hand', models.IntegerField(default=0)),
                ('sell_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('severity_rank', models.PositiveIntegerField(default=0)),
                ('refreshed_at', models.DateTimeField()),
                ('dashboard_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_preview', to='projections.shopdashboardsnapshot')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='low_stock_snapshots', to='inventory.inventoryitem')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_snapshots', to='shops.shop')),
            ],
            options={
                'ordering': ['severity_rank', 'stock_on_hand', 'item_name'],
            },
        ),
        migrations.AddIndex(
            model_name='shopdashboardsnapshot',
            index=models.Index(fields=['refreshed_at'], name='projections_refresh_125680_idx'),
        ),
        migrations.AddIndex(
            model_name='shoplowstocksnapshot',
            index=models.Index(fields=['shop', 'severity_rank'], name='projections_shop_id_407fcc_idx'),
        ),
        migrations.AddIndex(
            model_name='shoplowstocksnapshot',
            index=models.Index(fields=['dashboard_snapshot', 'severity_rank'], name='projections_dashboa_3d0695_idx'),
        ),
    ]
