# Generated by Django 6.0.4 on 2026-05-23 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projections', '0001_initial'),
        ('shops', '0005_workspaceaccesssession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPulseSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal_kind', models.CharField(choices=[('task', 'Task'), ('anomaly', 'Anomaly')], max_length=16)),
                ('code', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('signal_level', models.CharField(blank=True, max_length=16)),
                ('signal_rank', models.PositiveIntegerField(default=0)),
                ('tone', models.CharField(blank=True, max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('route', models.CharField(blank=True, max_length=128)),
                ('cta_label', models.CharField(blank=True, max_length=64)),
                ('metric_value', models.CharField(blank=True, max_length=64)),
                ('count', models.PositiveIntegerField(default=0)),
                ('first_detected_at', models.DateTimeField()),
                ('last_detected_at', models.DateTimeField()),
                ('last_snapshot_refreshed_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('acknowledged_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_pulse_signals', to=settings.AUTH_USER_MODEL)),
                ('resolved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_pulse_signals', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulse_signals', to='shops.shop')),
            ],
            options={
                'ordering': ['status', '-signal_rank', '-last_detected_at', 'title'],
                'indexes': [models.Index(fields=['shop', 'status', 'signal_kind'], name='projections_shop_id_e9a8dc_idx'), models.Index(fields=['shop', 'last_detected_at'], name='projections_shop_id_530c56_idx'), models.Index(fields=['shop', 'signal_rank'], name='projections_shop_id_6ca5a7_idx')],
                'constraints': [models.UniqueConstraint(fields=('shop', 'signal_kind', 'code'), name='uniq_shop_pulse_signal')],
            },
        ),
    ]
