# Generated by Django 6.0.4 on 2026-05-23 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projections', '0002_shoppulsesignal'),
        ('shops', '0005_workspaceaccesssession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppulsesignal',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppulsesignal',
            name='assigned_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workspace_pulse_signals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoppulsesignal',
            name='assigned_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pulse_signals', to='shops.shopmembership'),
        ),
        migrations.AddField(
            model_name='shoppulsesignal',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppulsesignal',
            name='escalated_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_workspace_pulse_signals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoppulsesignal',
            name='escalation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shoppulsesignal',
            name='follow_up_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shoppulsesignal',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='shoppulsesignal',
            index=models.Index(fields=['shop', 'is_escalated', 'status'], name='projections_shop_id_7c741f_idx'),
        ),
    ]
