# Generated by Django 6.0.4 on 2026-05-12 10:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0003_shop_domain_epoch_shop_invite_code_shop_migrated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPNextShopBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=16)),
                ('site_url_override', models.URLField(blank=True)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('warehouse', models.CharField(blank=True, max_length=255)),
                ('selling_price_list', models.CharField(blank=True, max_length=255)),
                ('cost_center', models.CharField(blank=True, max_length=255)),
                ('customer_group', models.CharField(blank=True, max_length=255)),
                ('supplier_group', models.CharField(blank=True, max_length=255)),
                ('currency_code', models.CharField(default='INR', max_length=8)),
                ('item_sync_enabled', models.BooleanField(default=True)),
                ('customer_sync_enabled', models.BooleanField(default=True)),
                ('stock_sync_enabled', models.BooleanField(default=True)),
                ('sales_posting_enabled', models.BooleanField(default=True)),
                ('payment_posting_enabled', models.BooleanField(default=True)),
                ('purchase_sync_enabled', models.BooleanField(default=False)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_status', models.CharField(choices=[('unknown', 'Unknown'), ('ok', 'OK'), ('degraded', 'Degraded'), ('error', 'Error'), ('misconfigured', 'Misconfigured')], default='unknown', max_length=16)),
                ('last_error_message', models.TextField(blank=True)),
                ('last_health_payload_json', models.JSONField(blank=True, default=dict)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='erpnext_binding', to='shops.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ERPNextDocumentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_domain', models.CharField(choices=[('item', 'Item'), ('customer', 'Customer'), ('sale', 'Sale'), ('payment', 'Payment'), ('purchase', 'Purchase')], max_length=24)),
                ('local_object_id', models.CharField(max_length=64)),
                ('remote_doctype', models.CharField(max_length=120)),
                ('remote_name', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('pull', 'Pull'), ('push', 'Push')], max_length=16)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('linked', 'Linked'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erpnext_document_links', to='shops.shop')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'local_domain', 'local_object_id', 'remote_doctype'), name='erpnext_unique_local_to_remote_link')],
            },
        ),
        migrations.CreateModel(
            name='ERPNextSyncCursor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(choices=[('items', 'Items'), ('customers', 'Customers'), ('stock', 'Stock'), ('sales', 'Sales'), ('payments', 'Payments'), ('suppliers', 'Suppliers'), ('purchases', 'Purchases')], max_length=24)),
                ('direction', models.CharField(choices=[('pull', 'Pull'), ('push', 'Push')], max_length=16)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='idle', max_length=16)),
                ('last_remote_modified_at', models.DateTimeField(blank=True, null=True)),
                ('last_remote_cursor', models.CharField(blank=True, max_length=255)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_result_count', models.PositiveIntegerField(default=0)),
                ('last_error_message', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erpnext_sync_cursors', to='shops.shop')),
            ],
            options={
                'ordering': ['domain', 'direction'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'domain', 'direction'), name='erpnext_unique_cursor_per_shop_domain_direction')],
            },
        ),
    ]
