# Generated by Django 6.0.4 on 2026-05-12 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpnext', '0001_initial'),
        ('shops', '0003_shop_domain_epoch_shop_invite_code_shop_migrated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpnextdocumentlink',
            name='local_domain',
            field=models.CharField(choices=[('item', 'Item'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('sale', 'Sale'), ('payment', 'Payment'), ('purchase', 'Purchase')], max_length=24),
        ),
        migrations.CreateModel(
            name='ERPNextSupplierMirror',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_name', models.CharField(max_length=255)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_group', models.CharField(blank=True, max_length=255)),
                ('supplier_type', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('last_remote_modified_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erpnext_suppliers', to='shops.shop')),
            ],
            options={
                'ordering': ['supplier_name', 'remote_name'],
            },
        ),
        migrations.CreateModel(
            name='ERPNextPurchaseMirror',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_doctype', models.CharField(default='Purchase Receipt', max_length=120)),
                ('remote_name', models.CharField(max_length=255)),
                ('supplier_remote_name', models.CharField(blank=True, max_length=255)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('warehouse', models.CharField(blank=True, max_length=255)),
                ('currency_code', models.CharField(default='INR', max_length=8)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('docstatus', models.IntegerField(default=0)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('items_json', models.JSONField(blank=True, default=list)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('last_remote_modified_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erpnext_purchases', to='shops.shop')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_documents', to='erpnext.erpnextsuppliermirror')),
            ],
            options={
                'ordering': ['-posting_date', '-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='erpnextsuppliermirror',
            constraint=models.UniqueConstraint(fields=('shop', 'remote_name'), name='erpnext_unique_supplier_mirror_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='erpnextpurchasemirror',
            constraint=models.UniqueConstraint(fields=('shop', 'remote_doctype', 'remote_name'), name='erpnext_unique_purchase_mirror_per_shop'),
        ),
    ]
