# Generated by Django 6.0.4 on 2026-05-13 06:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpnext', '0002_alter_erpnextdocumentlink_local_domain_and_more'),
        ('shops', '0003_shop_domain_epoch_shop_invite_code_shop_migrated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpnextpurchasemirror',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='erpnextpurchasemirror',
            name='return_against_remote_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='erpnextsynccursor',
            name='domain',
            field=models.CharField(choices=[('items', 'Items'), ('customers', 'Customers'), ('stock', 'Stock'), ('sales', 'Sales'), ('payments', 'Payments'), ('suppliers', 'Suppliers'), ('purchases', 'Purchases'), ('supplier_payments', 'Supplier payments')], max_length=24),
        ),
        migrations.CreateModel(
            name='ERPNextSupplierPaymentMirror',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_doctype', models.CharField(default='Payment Entry', max_length=120)),
                ('remote_name', models.CharField(max_length=255)),
                ('supplier_remote_name', models.CharField(blank=True, max_length=255)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=64)),
                ('mode_of_payment', models.CharField(blank=True, max_length=120)),
                ('reference_no', models.CharField(blank=True, max_length=255)),
                ('currency_code', models.CharField(default='INR', max_length=8)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('docstatus', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('last_remote_modified_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erpnext_supplier_payments', to='shops.shop')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_documents', to='erpnext.erpnextsuppliermirror')),
            ],
            options={
                'ordering': ['-posting_date', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'remote_doctype', 'remote_name'), name='erpnext_unique_supplier_payment_mirror_per_shop')],
            },
        ),
    ]
