# Generated by Django 6.0.4 on 2026-07-01 11:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_cgst_amount_sale_igst_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='line_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
