# Generated by Django 6.0.4 on 2026-07-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_saleitem_line_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='buyer_gstin',
            field=models.CharField(blank=True, help_text='GSTIN of the buyer for B2B sales', max_length=15, null=True),
        ),
    ]
