# Generated by Django 6.0.4 on 2026-04-30 06:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0003_shop_domain_epoch_shop_invite_code_shop_migrated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('source_shop_id', models.CharField(blank=True, max_length=128)),
                ('source_path', models.CharField(blank=True, max_length=255)),
                ('migrated_at', models.DateTimeField(blank=True, null=True)),
                ('domain_epoch', models.PositiveIntegerField(default=1)),
                ('session_date', models.DateField()),
                ('clock_in_at', models.DateTimeField(blank=True, null=True)),
                ('clock_out_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half day'), ('LEAVE', 'Leave')], default='ABSENT', max_length=16)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('tombstone', models.BooleanField(default=False)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='shops.shopmembership')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='shops.shop')),
            ],
            options={
                'ordering': ['-session_date', '-created_at'],
                'indexes': [models.Index(fields=['shop', 'session_date'], name='attendance__shop_id_06b766_idx'), models.Index(fields=['membership', 'session_date'], name='attendance__members_f57760_idx'), models.Index(fields=['shop', 'status'], name='attendance__shop_id_89255e_idx')],
                'constraints': [models.UniqueConstraint(fields=('shop', 'membership', 'session_date'), name='uniq_attendance_per_day')],
            },
        ),
    ]
