# Generated by Django 6.0.4 on 2026-04-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('shops', '0003_shop_domain_epoch_shop_invite_code_shop_migrated_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancesession',
            name='uniq_attendance_per_day',
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('tombstone', False)), fields=('shop', 'membership', 'session_date'), name='uniq_attendance_per_day'),
        ),
    ]
