# Generated by Django 6.0.4 on 2026-04-30 05:06

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0003_shop_domain_epoch_shop_invite_code_shop_migrated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('source_shop_id', models.CharField(blank=True, max_length=128)),
                ('source_path', models.CharField(blank=True, max_length=255)),
                ('migrated_at', models.DateTimeField(blank=True, null=True)),
                ('domain_epoch', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=128)),
                ('barcode', models.CharField(blank=True, max_length=128)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('subcategory', models.CharField(blank=True, max_length=120)),
                ('size', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('sell_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('draft', 'Draft')], default='active', max_length=16)),
                ('tombstone', models.BooleanField(default=False)),
                ('source_meta_json', models.JSONField(blank=True, default=dict)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItemPrivate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('source_shop_id', models.CharField(blank=True, max_length=128)),
                ('source_path', models.CharField(blank=True, max_length=255)),
                ('migrated_at', models.DateTimeField(blank=True, null=True)),
                ('domain_epoch', models.PositiveIntegerField(default=1)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('supplier_id', models.CharField(blank=True, max_length=128)),
                ('last_purchase_date', models.DateField(blank=True, null=True)),
                ('tombstone', models.BooleanField(default=False)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private', to='inventory.inventoryitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryStockLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('source_shop_id', models.CharField(blank=True, max_length=128)),
                ('source_path', models.CharField(blank=True, max_length=255)),
                ('migrated_at', models.DateTimeField(blank=True, null=True)),
                ('domain_epoch', models.PositiveIntegerField(default=1)),
                ('event_type', models.CharField(choices=[('opening_balance', 'Opening balance'), ('adjustment', 'Adjustment'), ('sale', 'Sale'), ('return', 'Return'), ('import', 'Import'), ('sync', 'Sync')], max_length=32)),
                ('quantity_delta', models.IntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('note', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_events', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='inventory.inventoryitem')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stock_ledger', to='shops.shop')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['shop', 'name'], name='inventory_i_shop_id_0f7952_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['shop', 'sku'], name='inventory_i_shop_id_33726e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['shop', 'category'], name='inventory_i_shop_id_8459c2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystockledger',
            index=models.Index(fields=['shop', 'occurred_at'], name='inventory_i_shop_id_dd1a29_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystockledger',
            index=models.Index(fields=['item', 'occurred_at'], name='inventory_i_item_id_c93733_idx'),
        ),
    ]
