# Generated by Django 6.0.4 on 2026-07-01 00:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='price_includes_tax',
            field=models.BooleanField(default=True),
        ),
    ]
