# Generated by Django 6.0.4 on 2026-04-30 12:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0003_shop_domain_epoch_shop_invite_code_shop_migrated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationReconciliationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(choices=[('shop_settings', 'Shop settings'), ('inventory', 'Inventory'), ('inventory_private', 'Inventory private'), ('customers', 'Customers'), ('customer_ledger', 'Customer ledger'), ('expenses', 'Expenses'), ('attendance', 'Attendance'), ('sales', 'Sales'), ('payments', 'Payments'), ('stock_ledger', 'Stock ledger'), ('reporting', 'Reporting')], max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='open', max_length=16)),
                ('issue_code', models.CharField(max_length=64)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(blank=True, max_length=128)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('expected_master', models.CharField(blank=True, max_length=32)),
                ('observed_source', models.CharField(blank=True, max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('mismatch_payload_json', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_migration_events', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_reconciliation_events', to='shops.shop')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['shop', 'domain'], name='audit_migra_shop_id_815d6f_idx'), models.Index(fields=['status', 'severity'], name='audit_migra_status_fc149c_idx'), models.Index(fields=['issue_code', 'occurred_at'], name='audit_migra_issue_c_11a8e3_idx')],
            },
        ),
    ]
