# Generated by Django 6.0.4 on 2026-05-23 07:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('shops', '0004_shopplanrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_role', models.CharField(blank=True, max_length=16)),
                ('category', models.CharField(choices=[('workspace', 'Workspace'), ('inventory', 'Inventory'), ('customer', 'Customer'), ('sale', 'Sale'), ('payment', 'Payment')], max_length=32)),
                ('event_type', models.CharField(max_length=64)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(blank=True, max_length=128)),
                ('entity_label', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField()),
                ('source_surface', models.CharField(blank=True, max_length=64)),
                ('before_json', models.JSONField(blank=True, default=dict)),
                ('after_json', models.JSONField(blank=True, default=dict)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_audit_events', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='shops.shop')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['shop', 'occurred_at'], name='audit_works_shop_id_1d73e8_idx'), models.Index(fields=['shop', 'category', 'occurred_at'], name='audit_works_shop_id_1b01ef_idx'), models.Index(fields=['actor_user', 'occurred_at'], name='audit_works_actor_u_fb7d72_idx'), models.Index(fields=['event_type', 'occurred_at'], name='audit_works_event_t_c68c84_idx')],
            },
        ),
    ]
