# Generated by Django 6.0.4 on 2026-04-30 05:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0003_shop_domain_epoch_shop_invite_code_shop_migrated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('source_shop_id', models.CharField(blank=True, max_length=128)),
                ('source_path', models.CharField(blank=True, max_length=255)),
                ('migrated_at', models.DateTimeField(blank=True, null=True)),
                ('domain_epoch', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='-', max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('tombstone', models.BooleanField(default=False)),
                ('source_meta_json', models.JSONField(blank=True, default=dict)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('source_shop_id', models.CharField(blank=True, max_length=128)),
                ('source_path', models.CharField(blank=True, max_length=255)),
                ('migrated_at', models.DateTimeField(blank=True, null=True)),
                ('domain_epoch', models.PositiveIntegerField(default=1)),
                ('event_type', models.CharField(choices=[('opening_balance', 'Opening balance'), ('sale', 'Sale'), ('payment', 'Payment'), ('adjustment', 'Adjustment'), ('import', 'Import'), ('sync', 'Sync')], max_length=32)),
                ('amount_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_spent_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_ledger_events', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='customers.customer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_ledger_entries', to='shops.shop')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['shop', 'name'], name='customers_c_shop_id_2bfbb8_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['shop', 'phone'], name='customers_c_shop_id_2daa30_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['shop', 'status'], name='customers_c_shop_id_38e0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledgerentry',
            index=models.Index(fields=['shop', 'occurred_at'], name='customers_c_shop_id_fb8908_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledgerentry',
            index=models.Index(fields=['customer', 'occurred_at'], name='customers_c_custome_f4f62b_idx'),
        ),
    ]
