# Generated by Django 6.0.4 on 2026-04-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='domain_epoch',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='migrated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='source_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='source_shop_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
