# Generated by Django 6.0.4 on 2026-05-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_platformuser_domain_epoch_platformuser_migrated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='mfa_totp_enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='mfa_totp_last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='mfa_totp_pending_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='mfa_totp_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
