# Generated by Django 6.0.4 on 2026-05-23 15:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_platformuser_mfa_totp_enabled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPasskeyCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('credential_id', models.CharField(max_length=255, unique=True)),
                ('public_key_spki', models.TextField()),
                ('cose_algorithm', models.IntegerField(default=-7)),
                ('sign_count', models.PositiveBigIntegerField(default=0)),
                ('transports_json', models.JSONField(blank=True, default=list)),
                ('aaguid', models.CharField(blank=True, max_length=36)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-last_verified_at', '-updated_at', 'label'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='users_userp_user_id_b6cf20_idx'), models.Index(fields=['user', 'updated_at'], name='users_userp_user_id_ca537a_idx')],
            },
        ),
    ]
