# Generated by Django 6.0.4 on 2026-04-30 12:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0003_shop_domain_epoch_shop_invite_code_shop_migrated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationDomainControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(choices=[('shop_settings', 'Shop settings'), ('inventory', 'Inventory'), ('inventory_private', 'Inventory private'), ('customers', 'Customers'), ('customer_ledger', 'Customer ledger'), ('expenses', 'Expenses'), ('attendance', 'Attendance'), ('sales', 'Sales'), ('payments', 'Payments'), ('stock_ledger', 'Stock ledger'), ('reporting', 'Reporting')], max_length=64)),
                ('write_master', models.CharField(choices=[('firebase', 'Firebase'), ('postgres', 'PostgreSQL')], default='firebase', max_length=16)),
                ('bridge_mode', models.CharField(choices=[('disabled', 'Disabled'), ('compare_only', 'Compare only'), ('firebase_to_postgres', 'Firebase to PostgreSQL'), ('postgres_to_firebase', 'PostgreSQL to Firebase')], default='disabled', max_length=24)),
                ('cutover_status', models.CharField(choices=[('legacy', 'Legacy'), ('pilot', 'Pilot'), ('ready', 'Ready'), ('postgres_primary', 'PostgreSQL primary')], default='legacy', max_length=24)),
                ('current_epoch', models.PositiveIntegerField(default=1)),
                ('shadow_reads_enabled', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_backfill_at', models.DateTimeField(blank=True, null=True)),
                ('last_shadow_verified_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_controls', to='shops.shop')),
            ],
            options={
                'ordering': ['shop__name', 'domain'],
                'indexes': [models.Index(fields=['shop', 'domain'], name='jobs_migrat_shop_id_e3bd09_idx'), models.Index(fields=['domain', 'write_master'], name='jobs_migrat_domain_e449d2_idx'), models.Index(fields=['domain', 'bridge_mode'], name='jobs_migrat_domain_edb479_idx')],
                'constraints': [models.UniqueConstraint(fields=('shop', 'domain'), name='uniq_migration_control_per_domain')],
            },
        ),
        migrations.CreateModel(
            name='MigrationJobRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(choices=[('shop_settings', 'Shop settings'), ('inventory', 'Inventory'), ('inventory_private', 'Inventory private'), ('customers', 'Customers'), ('customer_ledger', 'Customer ledger'), ('expenses', 'Expenses'), ('attendance', 'Attendance'), ('sales', 'Sales'), ('payments', 'Payments'), ('stock_ledger', 'Stock ledger'), ('reporting', 'Reporting')], max_length=64)),
                ('job_type', models.CharField(choices=[('backfill', 'Backfill'), ('shadow_compare', 'Shadow compare'), ('bridge_replay', 'Bridge replay'), ('projection_refresh', 'Projection refresh')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('trace_id', models.CharField(blank=True, max_length=128)),
                ('rows_scanned', models.PositiveIntegerField(default=0)),
                ('rows_written', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('mismatch_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_job_runs', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migration_job_runs', to='shops.shop')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain', 'job_type'], name='jobs_migrat_domain_f06240_idx'), models.Index(fields=['status', 'created_at'], name='jobs_migrat_status_7eee48_idx'), models.Index(fields=['shop', 'created_at'], name='jobs_migrat_shop_id_f4e4a1_idx')],
            },
        ),
    ]
