# Generated by Django 6.0.4 on 2026-04-30 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('shops', '0003_shop_domain_epoch_shop_invite_code_shop_migrated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationBridgeReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(choices=[('shop_settings', 'Shop settings'), ('inventory', 'Inventory'), ('inventory_private', 'Inventory private'), ('customers', 'Customers'), ('customer_ledger', 'Customer ledger'), ('expenses', 'Expenses'), ('attendance', 'Attendance'), ('sales', 'Sales'), ('payments', 'Payments'), ('stock_ledger', 'Stock ledger'), ('reporting', 'Reporting')], max_length=64)),
                ('origin_system', models.CharField(max_length=32)),
                ('origin_event_id', models.CharField(max_length=128)),
                ('command_type', models.CharField(blank=True, max_length=32)),
                ('entity_type', models.CharField(blank=True, max_length=64)),
                ('entity_id', models.CharField(blank=True, max_length=128)),
                ('base_domain_epoch', models.PositiveIntegerField(default=1)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('applied_at', models.DateTimeField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_bridge_receipts', to='shops.shop')),
            ],
            options={
                'ordering': ['-applied_at', '-created_at'],
                'indexes': [models.Index(fields=['shop', 'domain', 'applied_at'], name='jobs_migrat_shop_id_861d1a_idx'), models.Index(fields=['domain', 'origin_system'], name='jobs_migrat_domain_451c60_idx')],
                'constraints': [models.UniqueConstraint(fields=('shop', 'domain', 'origin_system', 'origin_event_id'), name='uniq_bridge_receipt_origin_event')],
            },
        ),
    ]
