# Generated by Django 6.0.4 on 2026-05-01 05:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_migrationbridgereceipt'),
        ('shops', '0003_shop_domain_epoch_shop_invite_code_shop_migrated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationControlEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(choices=[('shop_settings', 'Shop settings'), ('inventory', 'Inventory'), ('inventory_private', 'Inventory private'), ('customers', 'Customers'), ('customer_ledger', 'Customer ledger'), ('expenses', 'Expenses'), ('attendance', 'Attendance'), ('sales', 'Sales'), ('payments', 'Payments'), ('stock_ledger', 'Stock ledger'), ('reporting', 'Reporting')], max_length=64)),
                ('event_type', models.CharField(choices=[('prepare_pilot', 'Prepare pilot'), ('promote_ready', 'Promote ready'), ('promote_primary', 'Promote primary'), ('verify_pilot', 'Verify pilot'), ('rollback', 'Rollback')], max_length=32)),
                ('result', models.CharField(blank=True, max_length=32)),
                ('from_cutover_status', models.CharField(blank=True, max_length=24)),
                ('to_cutover_status', models.CharField(blank=True, max_length=24)),
                ('from_write_master', models.CharField(blank=True, max_length=16)),
                ('to_write_master', models.CharField(blank=True, max_length=16)),
                ('summary', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_control_events', to=settings.AUTH_USER_MODEL)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='jobs.migrationdomaincontrol')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_control_events', to='shops.shop')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['shop', 'domain', 'occurred_at'], name='jobs_migrat_shop_id_72958e_idx'), models.Index(fields=['event_type', 'occurred_at'], name='jobs_migrat_event_t_29f540_idx'), models.Index(fields=['result', 'occurred_at'], name='jobs_migrat_result_92b5ae_idx')],
            },
        ),
    ]
