# Generated by Django 6.0.4 on 2026-05-01 06:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_migrationcontrolevent'),
        ('shops', '0003_shop_domain_epoch_shop_invite_code_shop_migrated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationShopCheckpointEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('approved_for_cutover', 'Approved for cutover'), ('hold_for_monitoring', 'Hold for monitoring'), ('rollback_escalated', 'Rollback escalated')], max_length=32)),
                ('overall_status_snapshot', models.CharField(blank=True, max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('recommended_action_snapshot', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_shop_checkpoint_events', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_shop_checkpoint_events', to='shops.shop')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['shop', 'occurred_at'], name='jobs_migrat_shop_id_509009_idx'), models.Index(fields=['decision', 'occurred_at'], name='jobs_migrat_decisio_de1ad8_idx'), models.Index(fields=['overall_status_snapshot', 'occurred_at'], name='jobs_migrat_overall_3d6fb4_idx')],
            },
        ),
    ]
