# Generated by Django 6.0.4 on 2026-05-02 10:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_migrationrolloutcheckpointevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MigrationSteadyStateCheckpointEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phase", models.CharField(default="phase_8", max_length=32)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("accept_steady_state", "Accept steady state"),
                            ("hold_for_improvement", "Hold for improvement"),
                            ("architecture_review_required", "Architecture review required"),
                            ("incident_stabilization_active", "Incident stabilization active"),
                        ],
                        max_length=40,
                    ),
                ),
                ("overall_status_snapshot", models.CharField(blank=True, max_length=40)),
                ("summary", models.TextField(blank=True)),
                ("recommended_action_snapshot", models.TextField(blank=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField()),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="migration_steady_state_checkpoint_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["phase", "occurred_at"], name="jobs_migrat_phase_1717d8_idx"),
                    models.Index(fields=["decision", "occurred_at"], name="jobs_migrat_decisio_4cb812_idx"),
                    models.Index(
                        fields=["overall_status_snapshot", "occurred_at"],
                        name="jobs_migrat_overall_8df2c1_idx",
                    ),
                ],
            },
        ),
    ]
