# Generated by Django 6.0.4 on 2026-07-01 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_migrationsteadystatecheckpointevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='migrationgolivecheckpointevent',
            new_name='jobs_migrat_phase_65800e_idx',
            old_name='jobs_migrat_phase_4a84ab_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationgolivecheckpointevent',
            new_name='jobs_migrat_decisio_35c9fa_idx',
            old_name='jobs_migrat_decisio_10b86e_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationgolivecheckpointevent',
            new_name='jobs_migrat_overall_23af2b_idx',
            old_name='jobs_migrat_overall_9dca20_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationlaunchcheckpointevent',
            new_name='jobs_migrat_phase_b7a062_idx',
            old_name='jobs_migrat_phase_14d00f_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationlaunchcheckpointevent',
            new_name='jobs_migrat_decisio_bee70e_idx',
            old_name='jobs_migrat_decisio_086cca_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationlaunchcheckpointevent',
            new_name='jobs_migrat_overall_5253d6_idx',
            old_name='jobs_migrat_overall_55fe40_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationrolloutcheckpointevent',
            new_name='jobs_migrat_phase_4a391d_idx',
            old_name='jobs_migrat_phase_5b40ce_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationrolloutcheckpointevent',
            new_name='jobs_migrat_decisio_710772_idx',
            old_name='jobs_migrat_decisio_fad839_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationrolloutcheckpointevent',
            new_name='jobs_migrat_overall_d5f9ca_idx',
            old_name='jobs_migrat_overall_8ad09b_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationsteadystatecheckpointevent',
            new_name='jobs_migrat_phase_c3a142_idx',
            old_name='jobs_migrat_phase_1717d8_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationsteadystatecheckpointevent',
            new_name='jobs_migrat_decisio_d8b872_idx',
            old_name='jobs_migrat_decisio_4cb812_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationsteadystatecheckpointevent',
            new_name='jobs_migrat_overall_47f876_idx',
            old_name='jobs_migrat_overall_8df2c1_idx',
        ),
    ]
