# Generated by Django 6.0.4 on 2026-04-30 04:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('currency_code', models.CharField(default='INR', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='staff', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('permissions_version', models.PositiveIntegerField(default=1)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='shops.shop')),
            ],
        ),
    ]
