# Generated by Django 6.0.4 on 2026-04-30 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='domain_epoch',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shop',
            name='invite_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='shop',
            name='migrated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shop',
            name='settings_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='shop',
            name='source_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shop',
            name='source_shop_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='shopmembership',
            name='domain_epoch',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shopmembership',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='shopmembership',
            name='migrated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopmembership',
            name='permissions_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='shopmembership',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='shopmembership',
            name='source_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shopmembership',
            name='source_shop_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
