# Generated by Django 6.0.4 on 2026-05-23 05:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_domain_epoch_shop_invite_code_shop_migrated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPlanRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('source_shop_id', models.CharField(blank=True, max_length=128)),
                ('source_path', models.CharField(blank=True, max_length=255)),
                ('migrated_at', models.DateTimeField(blank=True, null=True)),
                ('domain_epoch', models.PositiveIntegerField(default=1)),
                ('current_plan_tier', models.CharField(max_length=16)),
                ('requested_plan_tier', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=16)),
                ('request_note', models.TextField(blank=True)),
                ('context_json', models.JSONField(blank=True, default=dict)),
                ('requested_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_plan_requests', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_requests', to='shops.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
