# Generated by Django 6.0.4 on 2026-05-23 09:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shopplanrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceAccessSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('source_shop_id', models.CharField(blank=True, max_length=128)),
                ('source_path', models.CharField(blank=True, max_length=255)),
                ('migrated_at', models.DateTimeField(blank=True, null=True)),
                ('domain_epoch', models.PositiveIntegerField(default=1)),
                ('app_instance_id', models.CharField(max_length=128)),
                ('membership_role_snapshot', models.CharField(default='staff', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('device_label', models.CharField(max_length=255)),
                ('platform_name', models.CharField(blank=True, max_length=64)),
                ('package_name', models.CharField(blank=True, max_length=255)),
                ('app_version', models.CharField(blank=True, max_length=64)),
                ('build_number', models.CharField(blank=True, max_length=32)),
                ('release_channel', models.CharField(blank=True, max_length=32)),
                ('release_tag', models.CharField(blank=True, max_length=64)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True)),
                ('wipe_requested_at', models.DateTimeField(blank=True, null=True)),
                ('wipe_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_sessions', to='shops.shopmembership')),
                ('revoked_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_workspace_access_sessions', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_sessions', to='shops.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_access_sessions', to=settings.AUTH_USER_MODEL)),
                ('wipe_requested_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wipe_requested_workspace_access_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['shop', 'status', 'last_seen_at'], name='shops_works_shop_id_550c46_idx'), models.Index(fields=['user', 'last_seen_at'], name='shops_works_user_id_a0f998_idx'), models.Index(fields=['shop', 'wipe_requested_at'], name='shops_works_shop_id_4f5400_idx')],
                'unique_together': {('user', 'shop', 'app_instance_id')},
            },
        ),
    ]
