# Generated by Django 6.0.4 on 2026-07-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_workspaceaccesssession'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='shop',
            name='region_code',
            field=models.CharField(default='IN', max_length=8),
        ),
        migrations.AddField(
            model_name='shop',
            name='state_code',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
